### ISSUE TITLE
Document conflict condition

### ISSUE THREAD

**Issue by Chronostasys** [bh90210/dron8s#24]
Hi, I'm using dron8s plugin in my drone to update my services in k8s cluster. I found that when I trigger cd on a deployment previously created by kubectl client, a conflict error will occur(like the image below).  
![image](https://user-images.githubusercontent.com/49905799/134760020-d07502b1-7c01-483b-9d34-b77b240257cc.png)  
And it took me some time to find out I have to transfer ownership to dron8s to avoid this error(reading this [doc](https://kubernetes.io/docs/reference/using-api/server-side-apply/))  
However, I can't find the field manager's name in dron8s documentation and have to search it in the drone8s source code.    
https://github.com/bh90210/dron8s/blob/03fc616ea0bc8a612ee3ae1b95f9c4c2a385ffa2/main.go#L155  
I think it might be better to document it in the project readme, or add a force-conflict flag in the ssa request. It may save a lot of time for people who want to migrate existing deployment to dron8s.

**Comment by bh90210** [comment]
thank you so much for opening the ticket, I will look into to asap!
